### ISSUE TITLE
The homepage won't allow me to become a contributor

### ISSUE THREAD

**Issue by chenshuiluke** [morriswchris/contributin#13]
![firefox_screenshot_2016-11-06t05-39-20 649z](https://cloud.githubusercontent.com/assets/7980284/20035600/9232ea92-a3b9-11e6-93cf-069dac7fc24a.png)

I did initially forget to accept the agreement, but I checked the box and I still can't get through.

**Comment by morriswchris** [comment]
@chenshuiluke sorry, I missed comment. I'll take a look tonight and see if I can fix this nbug

**Comment by morriswchris** [comment]
@chenshuiluke this should now be resolved. It was a type issue. 

Thanks for trying out contributin. Feel free to submit any enhancements!
